packages:
  - "apps/*"
  - "packages/*"
  - "infra/*"

catalogs:
  hono:
    hono: "4.7.2"
  drizzle:
    drizzle-orm: "0.39.3"
    drizzle-kit: "0.30.4"
    drizzle-zod: "0.5.1"
  clerk:
    "@clerk/backend": "1.24.1"

catalog:
  "@macknolandev/clerk-zod": "1.0.10"
  tailwindcss: "3.4.13"
  typescript: "5.6.3"
  lucide-react: "0.456.0"
  next: "15.1.6"
  react: "19.0.0"
  react-dom: "19.0.0"
  "@types/react-dom": "19.0.1"
  "@types/react": "19.0.1"
  clsx: "2.1.1"
  class-variance-authority: "0.7.0"
  luxon: "3.5.0"
  nanoid: "5.0.8"
  next-themes: "0.4.3"
  radash: "12.1.0"
  drizzle-orm: "0.39.3"
  drizzle-kit: "0.30.4"
  drizzle-zod: "0.5.1"
  sst: "3.9.10"
  zod: "3.24.2"
