/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GITHUB_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "apiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "postgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "vpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}